### ISSUE TITLE
After Installation Not Found

### ISSUE THREAD

**Issue by casidos** [abhikchakraborty/sqcrm#5]
Hello,

I follow the instructions in the documentation with a fresh ubuntu vps 

after the installation i got 

Not Found
The requested URL /modules/User/login was not found on this server.
Apache/2.4.7 (Ubuntu) Server at sqcrm.testdomain.com Port 80

And the URL point to 

http://sqcrm.testdomain.com/modules/User/login

Thanks for the help.

**Comment by abhikchakraborty** [comment]
Hello casidos,
Looks like the `.htaccess` is missing, You can create one on the project directory and  https://github.com/abhikchakraborty/sqcrm/blob/master/.htaccess

And also make sure mod re-write is enabled.

Let us know if this fixed the issue.

**Comment by casidos** [comment]
Hello,

I enable mod_rewrite using

a2enmod rewrite

.htaccess file is available in my /sqcrm folder

After restart apache2 I got a blank page and enable the error report in the config

Notice: Undefined variable: cfg_project_directory in /var/www/sqcrm/includes/autoload.conf.inc.php on line 9
Notice: Undefined variable: cfg_project_directory in /var/www/sqcrm/includes/autoload.conf.inc.php on line 9
Notice: Undefined variable: cfg_project_directory in /var/www/sqcrm/includes/autoload.conf.inc.php on line 9
Fatal error: Class 'BaseObject' not found in /var/www/sqcrm/class/core/radria/EventControler.class.php on line 23

**Comment by abhikchakraborty** [comment]
Hello casidos,
Looks like a bigger issue you have discovered for which we will work on the fix part.
In the mean while you can open
https://github.com/abhikchakraborty/sqcrm/blob/master/config.php
and change line `number 10` to 
```php
$cfg_project_directory = dirname(__FILE__) ;`
```

Or even you can hard code the path as `/var/www/sqcrm/` if its your root directory.

**Comment by abhikchakraborty** [comment]
Ignore 2nd step and make it as 
```php
spl_autoload_register(function ($class) {
  // Core radria objects
  $cfg_project_directory = str_replace('/includes','',dirname(__FILE__));
}
```

**Comment by casidos** [comment]
Just make the first change, 
(making the change in outload.conf.inc.php give the same error)

Now i got 

Warning: dir(/var/www/sqcrmincludes/): failed to open dir: No such file or directory in /var/www/sqcrm/includes/extraconfig.inc.php on line 7
Fatal error: Call to a member function read() on a non-object in /var/www/sqcrm/includes/extraconfig.inc.php on line 8

**Comment by abhikchakraborty** [comment]
Hey @casidos ,
Please revert the changes that you did, I just added a fix and just need to apply it on the config.php
Here is the commit https://github.com/abhikchakraborty/sqcrm/commit/7d4d65ccb03c93828aca4493b44b4e7b493ae8a0

Comment out line `8 to 10` and add below it
```php
$cfg_project_directory = dirname(__FILE__).'/';
```
You can let us know if this fixed the issue on https://github.com/abhikchakraborty/sqcrm/issues/6 so that we can close that task too.

**Comment by casidos** [comment]
I implement the change in my config.pho an got this output:

`Notice: Undefined index: cfg_full_path in /var/www/sqcrm/config.php on line 38`

`Notice: Undefined index: cfg_full_path in /var/www/sqcrm/config.php on line 39`

`Notice: Undefined variable: cfg_project_directory in /var/www/sqcrm/includes/autoload.conf.inc.php on line 9`

`Notice: Undefined variable: cfg_project_directory in /var/www/sqcrm/includes/autoload.conf.inc.php on line 9`

`Notice: Undefined variable: cfg_project_directory in /var/www/sqcrm/includes/autoload.conf.inc.php on line 9`

`Fatal error: Class 'BaseObject' not found in /var/www/sqcrm/class/core/radria/EventControler.class.php on line 23`

**Comment by abhikchakraborty** [comment]
Thats really weird, the whole point of having `spl_autoload_register` is to load the class files as needed.
Looks like something going wrong with your PHP installation. However here is a heck in https://github.com/abhikchakraborty/sqcrm/blob/master/includes/autoload.conf.inc.php
Comment `line 9 till 14`
And then add
```php
include_once($cfg_project_directory.'class/core/radria/BaseObject.class.php');
include_once($cfg_project_directory.'class/core/radria/Display.class.php');
include_once($cfg_project_directory.'class/core/radria/EventControler.class.php');
include_once($cfg_project_directory.'class/core/radria/Event.class.php');
include_once($cfg_project_directory.'class/core/radria/DataObject.class.php');

```
And see if this fixes.

**Comment by casidos** [comment]
Now is working,

FYI my installation PHP is directly from LAMP in ubuntu 14.04 new server.

**Comment by abhikchakraborty** [comment]
Yes `ubuntu 14.04` is the recent one and PHP version is pretty higher `=>5.4` so it should support `spl_autoload_register`

Now the issue that you faced we had that in the earlier phase of the development. However we fixed this and tried sqcrm on different machines with new installations and it worked. We will keep an eye on it, thanks for bringing up the issue.
