### ISSUE TITLE
Thumbnail folder is not created.

### ISSUE THREAD

**Issue by casidos** [abhikchakraborty/sqcrm#8]
After edit my user profile,

I upload a picture to use as avatar the thumb folder in cache was not created, so the images was not displayed.

I create manually the thumb folder and give 0777 permission.

**Comment by abhikchakraborty** [comment]
Hmm,
There are currently 4 folders that should be there I will check the installation for now you need

`cache/thumb`
`cache/imports`
`cache/outbound`
`cache/uploads`
and all with 777 permission.

**Comment by casidos** [comment]
I only have uploads in my installation.

**Comment by abhikchakraborty** [comment]
This has been fixed and merged https://github.com/abhikchakraborty/sqcrm/commit/d18521949405bb9aa4361b09e9d0b78112ff96c8
